import React from "react";
import Box from "@mui/material/Box";
import { useTheme } from "@mui/material/styles";
import { Typography } from "@mui/material";
import AppBar from "@mui/material/AppBar";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import PropTypes from "prop-types";
import Table from "../Table/Table";
import Chart from "../Chart/Chart";
import jsonData from "../../../../../data/fastp.json";
import { BarChart } from "@mui/x-charts/BarChart";
import CharContent from "../ChartContent/CharContent";
import Heatmap from "../Heatmap/Heatmap";
import Grid from "@mui/material/Grid";
import { useMediaQuery } from "@mui/material";

function CustomTabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

CustomTabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

function Hero() {
  const isMobile = useMediaQuery((theme) => theme.breakpoints.down("sm"));
  const [value, setValue] = React.useState(0);
  const handleChange = (event, newValue) => {
    setValue(newValue);
  };
  const summaryData = jsonData.summary;
  const adapterData = jsonData.adapter_cutting;
  const duplicationData = jsonData.duplication;
  const duplicationDataHistogram = duplicationData.histogram;
  const inserSizeData = jsonData.insert_size;
  const inserSizeDataHistogram = inserSizeData.histogram;
  const readUnBeforeFiltering = jsonData.read1_before_filtering;
  const readUnBeforeFilteringLineChart = readUnBeforeFiltering.quality_curves;
  const QualityreadUnBeforeFilteringLineChart =
    readUnBeforeFilteringLineChart.A;
  console.log(jsonData.read1_after_filtering.kmer_count);

  let inserSizeDataHistogramXaxis = [];
  let index = 0;
  for (let elem of inserSizeDataHistogram) {
    inserSizeDataHistogramXaxis.push(index);
    index++;
  }
  let duplicationDataHistogramXaxis = [];
  let indexDuplication = 0;
  for (let elemDupli of duplicationDataHistogram) {
    duplicationDataHistogramXaxis.push(indexDuplication);
    indexDuplication++;
  }

  let LineChartXaxis = [];
  let indexQuality = 0;
  for (let elemQuality of QualityreadUnBeforeFilteringLineChart) {
    LineChartXaxis.push(indexQuality);
    indexQuality++;
  }
  return (
    <Box sx={{ width: "100%", display: "flex", flexDirection: "column" }}>
      <Box position="relative" zIndex={2}>
        <Box marginBottom={2}>
          <Typography
            variant="h2"
            align={"center"}
            sx={{
              fontWeight: 700,
            }}
          >
            FastP Dashboard
          </Typography>
        </Box>
        <Box marginBottom={4}>
          <Typography variant="h6" align={"center"} color={"textSecondary"}>
            When analyzing NGS (New Generation Sequencing) data, one of the
            first step is to check the quality of the data with FastP tool.
            <br />
            FastPis a powerful tool but the output (Json file) can be difficult
            to read for users without experience in bioinformatics field. This
            dashboard provides an easy way to visualize and analyze the output
            files generated by FastP (JSON).
            <br />
            This project was a good practice on ReactJS library, Material UI and
            Data visualization in JavaScript. You can upload your JSON file here
            or use our demo dataset below.
          </Typography>
        </Box>
        <Grid container direction="row" spacing={2}>
          <Grid
            item
            xs={12}
            sm={12}
            md={12}
            lg={12}
            alignItems={"center"}
            sx={{ flexGrow: 0 }}
          >
            <Tabs
              value={value}
              onChange={handleChange}
              centered
              color="primary"
              variant="scrollable"
              scrollButtons
              allowScrollButtonsMobile
              sx={{ display: { xs: "flex", md: "none" } }}
            >
              <Tab label="Overview" {...a11yProps(0)} />
              <Tab label="Adapters" {...a11yProps(1)} />
              <Tab
                label="Duplication & Insert size distribution"
                {...a11yProps(2)}
              />
              <Tab label="Before filtering" {...a11yProps(3)} />
              <Tab label="After filtering" {...a11yProps(4)} />
            </Tabs>
            <Tabs
              value={value}
              onChange={handleChange}
              centered
              color="primary"
              variant="fullWidth"
              sx={{ display: { xs: "none", md: "flex" } }}
            >
              <Tab label="Overview" {...a11yProps(0)} />
              <Tab label="Adapters" {...a11yProps(1)} />
              <Tab
                label="Duplication & Insert size distribution"
                {...a11yProps(2)}
              />
              <Tab label="Before filtering" {...a11yProps(3)} />
              <Tab label="After filtering" {...a11yProps(4)} />
            </Tabs>
          </Grid>
          <Grid container direction="row" spacing={2}>
            <Grid item xs={12} sm={12} md={16} lg={16}>
              <CustomTabPanel value={value} index={0} centered>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Table
                      title="Before Filtering"
                      section="before_filtering"
                      summaryData={summaryData.before_filtering}
                      headersKey=""
                      headersValue=""
                    />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Table
                      title="After Filtering"
                      section="after_filtering"
                      summaryData={summaryData.after_filtering}
                      headersKey=""
                      headersValue=""
                    />
                  </Grid>
                </Grid>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Table
                      title="Filtering Results"
                      section="after_filtering"
                      summaryData={jsonData.filtering_result}
                      headersKey=""
                      headersValue=""
                    />
                  </Grid>
                </Grid>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={1}>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Table
                      title="Adapter or bad ligation of read1"
                      section="adapter_read1"
                      summaryData={adapterData.read1_adapter_counts}
                      headersKey="Sequence"
                      headersValue="Occurrences"
                    />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Table
                      title="Adapter or bad ligation of read2"
                      section="adapter_read2"
                      summaryData={adapterData.read2_adapter_counts}
                      headersKey="Sequence"
                      headersValue="Occurrences"
                    />
                  </Grid>
                </Grid>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={2}>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        width: "100%",
                      }}
                    >
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h2>Duplication</h2>
                      </Box>
                      <BarChart
                        series={[{ data: duplicationDataHistogram }]}
                        height={390}
                        xAxis={[
                          {
                            data: duplicationDataHistogramXaxis,
                            scaleType: "band",
                          },
                        ]}
                        /* margin={{ top: 10, bottom: 30, left: 40, right: 10 }} */
                      />
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        width: "100%",
                      }}
                    >
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h2>Insert size distribution</h2>
                      </Box>
                      <BarChart
                        series={[{ data: inserSizeDataHistogram }]}
                        height={390}
                        xAxis={[
                          {
                            data: inserSizeDataHistogramXaxis,
                            scaleType: "band",
                          },
                        ]}
                        /* margin={{ top: 10, bottom: 30, left: 40, right: 10 }} */
                      />
                    </Box>
                  </Grid>
                </Grid>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={3}>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h2>Before filtering</h2>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ textAlign: "center" }}>
                      <h4>Quality Curves</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h4>Read 1</h4>
                    </Box>
                    <Chart typeFiltering="ReadUnBeforeFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h4>Read 2</h4>
                    </Box>
                    <Chart typeFiltering="ReadTwoBeforeFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ textAlign: "center" }}>
                      <h4>Base Contents</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    {isMobile && (
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h4>Read 1</h4>
                      </Box>
                    )}
                    <CharContent typeFiltering="ReadUnBeforeFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    {isMobile && (
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h4>Read 2</h4>
                      </Box>
                    )}
                    <CharContent typeFiltering="ReadTwoBeforeFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      <h4>Kmer Counting</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      {isMobile && <h4>Read 1</h4>}
                      <Heatmap />
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      {isMobile && <h4>Read 2</h4>}
                      <Heatmap />
                    </Box>
                  </Grid>
                </Grid>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={4}>
                <Grid
                  container
                  direction="row"
                  spacing={2}
                  justifyContent="center"
                  justifyItems="center"
                >
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h2>After filtering</h2>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ textAlign: "center" }}>
                      <h4>Quality Curves</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h4>Read 1</h4>
                    </Box>
                    <Chart typeFiltering="ReadUnAfterFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ p: 2, textAlign: "center" }}>
                      <h4>Read 2</h4>
                    </Box>
                    <Chart typeFiltering="ReadTwoAfterFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box sx={{ textAlign: "center" }}>
                      <h4>Base Contents</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    {isMobile && (
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h4>Read 1</h4>
                      </Box>
                    )}
                    <CharContent typeFiltering="ReadUnAfterFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    {isMobile && (
                      <Box sx={{ p: 2, textAlign: "center" }}>
                        <h4>Read 2</h4>
                      </Box>
                    )}
                    <CharContent typeFiltering="ReadTwoAfterFiltering" />
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={12}
                    lg={12}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      <h4>Kmer Counting</h4>
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      {isMobile && <h4>Read 1</h4>}
                      <Heatmap />
                    </Box>
                  </Grid>
                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={6}
                    lg={6}
                    justifyContent="center"
                    justifyItems="center"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "flex-start",
                        justifyContent: "space-around",
                      }}
                    >
                      {isMobile && <h4>Read 2</h4>}
                      <Heatmap />
                    </Box>
                  </Grid>
                </Grid>
              </CustomTabPanel>
            </Grid>
          </Grid>
        </Grid>
      </Box>
    </Box>
  );
}

export default Hero;
